"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.join(__dirname,".."),graphPath=path.join(root,"skills/life-wiki/assets/viewer/graph.js"),source=fs.readFileSync(graphPath,"utf8"),{graphModel}=require(graphPath);
const wiki=JSON.parse(fs.readFileSync(path.join(root,"examples/expected/wiki.json"),"utf8"));
const full=graphModel(wiki,wiki.cards);
assert.equal(full.nodes.length,4);assert.equal(full.edges.length,2);assert.deepEqual(full.edges.map(e=>e.id),wiki.relations.map(e=>e.id));
assert.equal(full.edges.find(e=>e.type==="possible_same_work").certainty,"uncertain");
for(const n of full.nodes)assert(Math.abs(n.x*n.x+n.y*n.y+n.z*n.z-1)<1e-10);
assert.equal(graphModel(wiki,[wiki.cards[0]]).edges.length,0);assert.equal(graphModel(wiki,[]).nodes.length,0);
assert(!/\b(fetch|XMLHttpRequest|WebSocket|localStorage|sessionStorage|sendBeacon|innerHTML|outerHTML|insertAdjacentHTML)\b/.test(source));
const calls=[],ctx={setTransform(){},clearRect(){},fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){calls.push(["edge",this.lineWidth]);},arc(x,y,r){calls.push(["node",x,y,r]);},fill(){},fillText(text){calls.push(["text",text]);},setLineDash(values){calls.push(["dash",values]);}};
const events={},canvas={width:0,height:0,getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:800,height:440}),addEventListener:(name,fn)=>{events[name]=fn;},setPointerCapture(){}};
let selected=null;
const context={window:{devicePixelRatio:1,addEventListener(){},removeEventListener(){}},console};vm.createContext(context);vm.runInContext(source,context);
context.canvas=canvas;context.onSelect=id=>{selected=id;};vm.runInContext("controller=mountGraph(canvas,onSelect)",context);
context.controller.update(full,null);assert.equal(calls.filter(c=>c[0]==="edge").length,2);assert.equal(calls.filter(c=>c[0]==="node").length,4);assert(calls.some(c=>c[0]==="dash"&&c[1].length===2));
const node=calls.find(c=>c[0]==="node");events.pointerdown({clientX:node[1],clientY:node[2],pointerId:1});events.pointerup({clientX:node[1],clientY:node[2],pointerId:1});assert(selected);
calls.length=0;events.pointerdown({clientX:100,clientY:100,pointerId:1});events.pointermove({clientX:130,clientY:115});events.pointerup({clientX:130,clientY:115});assert.equal(calls.filter(c=>c[0]==="edge").length,2);
calls.length=0;events.wheel({deltaY:-200,preventDefault(){}});assert.equal(calls.filter(c=>c[0]==="node").length,4);events.keydown({key:"Home",preventDefault(){}});
context.controller.update(graphModel(wiki,[]),null);assert(calls.some(c=>c[0]==="text"&&c[1].includes("표시할 기록")));
console.log("Graph: evidence-only edges, uncertainty, filtering, spherical coordinates, canvas drawing, selection, rotation, zoom, keyboard reset, and empty state passed.");
